### ISSUE TITLE
Add helpers to decode any number to int64/double

### ISSUE THREAD

**Issue by rtsisyk** [rtsisyk/msgpuck#14]
Proposal 1:

```
/*
 * Decodes an integer or a floting point value as double.
 *
 * \param data the pointer to a buffer
 * \param deflt a value to return on error
 * \retval number on success
 * \retval deflt on overflow
 * \retval deflt if underlying mp type is not MP_INT, MP_UINT,
 *         MP_FLOAT or MP_DOUBLE.
 */
static inline double
mp_read_double(const char **data, double deflt);

/*
 * Decodes an integer value as int64_t.
 *
 * \param data the pointer to a buffer
 * \param deflt a value to return on error
 * \retval number on success
 * \retval deflt on overflow
 * \retval deflt if underlying mp type is not MP_INT, MP_UINT.
 */
static inline double
mp_read_int64(const char **data, int64_t deflt);
```

Proposal 2:
```
/*
 * Decodes an integer or a floting point value as double.
 *
 * \param[out] ret return value
 * \retval  0 on success
 * \retval -1 on overflow, *ret is set to zero
 * \retval -1 if underlying mp type is not MP_INT, MP_UINT,
 *         MP_FLOAT or MP_DOUBLE, *ret is set to zero.
 */
static inline int
mp_read_double(const char **data, double *ret);

/*
 * Decodes an integer value as int64_t.
 *
 * \param[out] ret return value
 * \retval  0 on success
 * \retval -1 on overflow, *ret is set to zero
 * \retval -1 if underlying mp type is not MP_INT, MP_UINT, *ret is set to zero
 */
static inline int
mp_read_int64(const char **data, int64_t *ret);
```

mp_decode_double() is already used, mp_decode_int64() is reserved for the future.
Any other ideas?

1. mp_read_int64
2. mp_convert_int64
3. mp_to_int64
4. mp_decode_int/mp_decode_double and rename current mp_decode_int()/mp_decode_double() to mp_decode_i64()/mp_decode_f64()

**Comment by dedok** [comment]
I'd like 'Proposal 2:' because I can have errors, that is very important in my cases.

**Comment by rtsisyk** [comment]
I personally like #2 with mp_read_int64() name.

**Comment by alyapunov** [comment]
1.
Decodes an integer value as **int64_t**.
...
static inline **double** mp_read_int64(const char **data, int64_t deflt);

2.
Decodes an integer value as **double**.
...
static inline int mp_read_int64(const char **data, **int64_t** *ret);

It seems to be a mistake here, I do not understand the logic.

**Comment by alyapunov** [comment]
I'd prefer (2)
I also think that different return codes would be more useful (-1 overflow, -2  wrong type)
BTW, what is 'overflow' in case of decoding double?

**Comment by rtsisyk** [comment]
> static inline int mp_read_int64(const char **data, int64_t *ret);

It seems to be a mistake here

Yeah, it just a mistake. I'll fix it in-place.

> BTW, what is 'overflow' in case of decoding double?

For example, an attempt to decode 1<<53 value from uint64_t to double. It is not literaly overflow, but rather "precision loss".

BTW, what is about naming?

**Comment by dedok** [comment]
I'd like the fourth option (4), decode naming conversion is better - IMHO
